- name: Install Nginx
  hosts: windows_servers
  tasks:
    - name: Install Nginx using Chocolatey
      win_chocolatey:
        name: nginx
        state: present

    - name: Copy Nginx config
      win_copy:
        src: /path/to/nginx.conf
        dest: C:\nginx\conf\nginx.conf
        
    - name: Install NSSM
      win_chocolatey:
        name: nssm
        state: present

    - name: Set up Nginx service using win_nssm
      win_nssm:
        name: nginx
        program: C:\nginx\nginx.exe
        args: -g "daemon off;"
        state: started
        user: Administrator
        password: YourAdminPassword
