apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:latest
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "dhirajD12"
            - name: MYSQL_DATABASE
              value: "userdata"
            - name: MYSQL_USER
              value: "root"
            - name: MYSQL_PASSWORD
              value: "dhirajD12"
          ports:
            - containerPort: 3306
