apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring
  labels:
    app: two-tier-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: two-tier-app
  template:
    metadata:
      labels:
        app: two-tier-app
    spec:
      containers:
        - name: spring
          image: devdhiraj12/spring:latest
          env:
            - name: MYSQL_HOST
              value: "10.100.38.79"          # this is your mysql's service clusture IP, Make sure to change it with yours
            - name: MYSQL_PASSWORD
              value: "dhirajD12"
            - name: MYSQL_USER
              value: "root"
            - name: MYSQL_DB
              value: "userdata"
          ports:
            - containerPort: 8080
          imagePullPolicy: Always
